- name: Create .config/dunst dir
  file:
    state: directory
    path: "{{desktop_user_vars.dir}}/.config/dunst"
- name: Configure dunstrc
  copy:
    src: dunst/dunstrc
    dest: "{{desktop_user_vars.dir}}/.config/dunst/dunstrc"
