- name: ensure foot config dir is present
  file:
    path: "{{ desktop_user_vars.dir }}/.config/foot"
    state: directory
- name: setup foot config
  copy:
    src: foot/foot.ini
    dest: "{{ desktop_user_vars.dir }}/.config/foot/foot.ini"
