---
- name: rofi
  include_tasks: rofi.yml
- name: xkb
  include_tasks: xkb.yml
- name: light locker
  include_tasks: light-locker.yml
  when: '"xmonad" in desktop_wm_list'
- name: xmonad conf
  include_tasks: xmonad-conf.yml
  when: '"xmonad" in desktop_wm_list or "matexmonad" in desktop_wm_list'
- name: desktop images
  include_tasks: desktop-images.yml
- name: nitogren
  include_tasks: nitrogen.yml
  when: '"xmonad" in desktop_wm_list'
- name: hidpi for xmonad
  include_tasks: hidpi.yml
  when:
    - '"xmonad" in desktop_wm_list or "matexmonad" in desktop_wm_list'
    - hi_dpi is defined and hi_dpi
- name: picom
  include_tasks: picom.yml
  when: '"xmonad" in desktop_wm_list'
- name: xinit
  include_tasks: xinitrc.yml
  when: '"matexmonad" in desktop_wm_list'
- name: kde i3
  include_tasks: kdei3.yml
  when: '"kdei3" in desktop_wm_list'
- name: dunst
  include_tasks: dunst.yml
  when: '"xmonad" in desktop_wm_list or "matexmonad" in desktop_wm_list'
- name: dconf
  include_tasks: dconf-settings.yml
  when: '"xmonad" in desktop_wm_list or "matexmonad" in desktop_wm_list'
- name: fonts
  include_tasks: fonts.yml
- name: sway configs
  include_tasks: sway.yml
  when: '"sway" in desktop_wm_list'
- include_tasks: foot.yml
