---
- include_tasks: systemd-user.yml
- name: Setup picom user service
  copy:
    src: picom.service
    dest: "{{ desktop_user_vars.dir }}/.config/systemd/user/picom.service"
  notify: [ 'systemd user' ]
- meta: flush_handlers
- name: Enable and start picom
  service:
    name: picom
    state: started
    enabled: yes
    user: yes
  environment:
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ desktop_user_vars.uid }}/bus"
