- name: ensure sway config dir is present
  file:
    path: "{{ desktop_user_vars.dir }}/.config/sway"
    state: directory
- name: setup sway config
  template:
    src: sway/config
    dest: "{{ desktop_user_vars.dir }}/.config/sway/config"
