- name: ensure xkb config dir is present
  file:
    path: "{{ desktop_user_vars.dir }}/.xkb/symbols"
    state: directory
- name: setup xkb hhk
  copy:
    src: xkb/hhk
    dest: "{{ desktop_user_vars.dir }}/.xkb/symbols/hhk" 
